---

- name: Debian | add software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success

# - name: Debian | add ansible repository for latest releases
#   apt_repository: repo='ppa:ansible/ansible'

- name: Import microsoft for azure-cli
  ansible.builtin.import_tasks: microsoft.yml

- name: Debian | orchestrator tools
  ansible.builtin.apt:
    name: "{{ orchestrator_pkg }}"
    state: "present"
    update_cache: "yes"
  register: pkg_result
  until: pkg_result is success

- name: Download vagrant
  ansible.builtin.get_url:
    url: "{{ orchestrator_vagrant_url_deb }}"
    dest: "{{ install_archives }}/{{ orchestrator_vagrant_url_deb | basename }}"
    checksum: "{{ orchestrator_vagrant_url_deb_hash | default(omit) }}"
    mode: '0644'

- name: Install vagrant
  ansible.builtin.apt:
    deb: "{{ install_archives }}/{{ orchestrator_vagrant_url_deb | basename }}"
  register: pkg_result
  until: pkg_result is success
